version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y php
  build:
    commands:
      - echo "Building the Tic Tac Toe Game"
  post_build:
    commands:
      - echo "Starting PHP Built-in Web Server"
      - php -S 0.0.0.0:8080 -t /path/to/your/application &
artifacts:
  files:
    - '**/*'
  discard-paths: no
